server:
  port: 8088
spring:
  application:
    name: feign-client
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream