server:
  port: 8769
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka
zuul:
  routes:
    userapi:
      path: /user/**
      serviceId: userservice
    orderapi:
      path: /order/**
      serviceId: orderservice

