server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true # 开启确认消息是否到达交换器，需要设置 true
    publisher-returns: true # 开启确认消息是否到达队列，需要设置 true